pipeline {     
    agent any
    parameters{        

        string(name: 'BRANCH_NAME',                           
        defaultValue: 'master',
        description: 'Repository Branch')
        
        string(name: 'URL_REPOSITORY',                           
        defaultValue: 'https://github.com/J0hann48/integracion_continua_backend.git',
        description: 'Repository name')
        
        string(name: 'VERSION',
        defaultValue: '1.0.0-SNAPSHOT',
        description: 'Product Version')

    }

    stages {
         stage('Deploy frontend') {
                    steps {
                        script {
                            sh("docker stop carrito-compras-frontend")                                       
                            sh("docker run --network network_name --name carrito-compras-frontend -p 80:80 j0h4nn/carrito-compras-frontend:latest")
                        }                
                    }
                }
    }
}